apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: node-jobs
          image: pedoelski/node-jobs:v1.0
